# Default values for spring-boot-app-demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
namespace: product-material-pass

image:
  repository: muhammadsaudkhan/spring-boot-app-demo
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1.PI4.S4"

imagePullSecrets: []
nameOverride: "spring-boot-app-demo"
fullnameOverride: "spring-boot-app-demo"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  #className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  hosts:
    - host: materialpass.int.demo.catena-x.net
      paths:
        - path: /hello
          pathType: Prefix
  tls:
    - secretName: tls-secret
      hosts:
        - materialpass.int.demo.catena-x.net

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
