apiVersion: v1
kind: Service
metadata:
  name: {{ include "spring-boot-app-demo.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "spring-boot-app-demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}    # host port
      targetPort: 8080                    # container port
      protocol: TCP
      name: http
  selector:
    {{- include "spring-boot-app-demo.selectorLabels" . | nindent 4 }}

